# Generated by Django 5.0.1 on 2024-01-26 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='birth',
            field=models.DateField(),
        ),
    ]
