# Generated by Django 5.0.1 on 2024-01-27 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_helpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountsmodel',
            name='helps',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.helpmodel'),
        ),
    ]
