# Generated by Django 5.0.1 on 2024-01-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_accountsmodel_helps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountsmodel',
            name='helps',
        ),
        migrations.AddField(
            model_name='accountsmodel',
            name='helps',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='accounts.helpmodel'),
        ),
    ]
