# Generated by Django 5.0.1 on 2024-01-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_accountsmodel_helps_accountsmodel_helps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountsmodel',
            name='helps',
            field=models.ManyToManyField(blank=True, default=None, to='accounts.helpmodel'),
        ),
    ]
